### ISSUE TITLE
motd

### ISSUE THREAD

**Issue by ngalfas** [tprelog/iocage-node-red#3]
I see that now you use 
usr_home=/var/db/nodered

still, motd says 
- Plugin directory for Node-RED
    /usr/home/nodered

- Plugin default Node-RED settings
    /usr/home/nodered/settings.js

**Comment by Ekristoffe** [comment]
Hello I think a fork and pull request would be faster to correct that one.
Ps which one should be the best for us ? keep the /usr/home or /var/db ?
I personally think the default /usr/home would be fine.
Maybe I miss something ?

**Comment by tprelog** [comment]
So yea, :facepalm:  I really dropped the ball on this one. Sorry guys. It should be fixed now

@Ekristoffe I already made this change a few months ago in the service script - To switch it again would cause a breaking change for everyone. However you are still free to change the directory on your own system. As long as you set this using `sysrc`, it will not be overwritten by future updates.
```
service nodered stop
sysrc nodered_config_dir=/path/to/directory
service nodered start
```

**EDIT** Just another quick note. If you'd rather the default location be moved, I would be willing to do so, however rather than have a breaking change now, I think this would be a change to make beginning with any 12.x release of this plugin.

**Comment by Ekristoffe** [comment]
It is just I was wondering if why this change.

**Comment by tprelog** [comment]
> It is just I was wondering if why this change.

`/usr/home` was never really a default, is was just the first location _I picked_. I noticed some other plugins use the `/var/db/${application_name}` path and since the `nodered` user is meant only to run Node-RED I decided to change it.

Also, I figured if a user wanted to mount an external dataset for the `nodered_config_dir`  the home directory paths would be available mount points

**Comment by Ekristoffe** [comment]
thanks

**Comment by Ekristoffe** [comment]
Ps you can close this issue
