### ISSUE TITLE
Plugin Version number missing

### ISSUE THREAD

**Issue by Ekristoffe** [tprelog/iocage-node-red#6]
Hello,
Would it be possible to have the plugin version number displayed in FreeNAS ?
This could be a big plus to check for updates.
Thanks.

**Comment by tprelog** [comment]
It was [explained to me is that the version comes from a BSD package](https://github.com/ix-plugin-hub/iocage-plugin-index/issues/47) ( so this version number gets pulled from the pkg site ) 

For Node-RED, I believe it can updated from it's own web interface so I don't think there is any need to wait for some sort of "plugin update" in order to update the application itself.

In this case, as well as some other plugins like ESPHome, TasmoAdmin and Home Assistant Core, there is no BSD package to pull a version from so the version is always NA

I agree 1000% and also wish the was a separate, _plugin version_ listed in the FreeNAS UI. Maybe I could start adding a release tag when I make an update to the plugin. This wouldn't be so much an actual release but at least a marked point in time to see when and what changes have been made. Still only small improvement on it's own, but maybe a simple sensor in Home Assistant to watch for new _plugin updates_ could work -- Or better yet, we all go bug IX-Systems to add a "plugin version" to the FreeNAS UI

**Comment by Ekristoffe** [comment]
Hello unfortunately i don't think node-red can update itself.
Same thing with node-red can't restart itself.
I think we need to use npm command for an update.
(depending on how it was installed this can be tricky, global or local).

**Comment by tprelog** [comment]
I can look at adding something to the RC script if needed. At least the plugin being a somewhat controller environment I can know how Node-RED is installed so hopefully wouldn't be too difficult or we can change the install to make updates as easy as possible ?

:thinking:  I thought an update for Node-RED would show as a update button here. It's not that easy?
![image](https://user-images.githubusercontent.com/35702532/84597848-9df78c00-ae34-11ea-8a9b-768ff141c09e.png)

**Comment by Ekristoffe** [comment]
I don't remember.
In docker I need to pull again the container in order to update Node-RED.
We will see with the next release of Node-RED.

**Comment by Ekristoffe** [comment]
Hello node-red just been updated 1.1.0 and no update button appears in node-red.

**Comment by tprelog** [comment]
@Ekristoffe -- Thanks for confirming... I'll add a new "update" function to the Node-RED rc service script.

Shouldn't take too long but I need to leave for work right now. I've quickly tested and these manual update steps seem to have worked on my system. If you want to upgrade Node-RED now, without waiting for me to update anything...
```
iocage console $_JAIL

# Stop Node-RED
service nodered stop

# Not sure this step is needed, but my update process seemed to hang without it
/usr/local/bin/npm cache clean --force

# Update Node-RED
setenv PYTHON /usr/local/bin/python2.7
npm install -g --unsafe-perm node-red

#Start Node-RED
service nodered start
```

![image](https://user-images.githubusercontent.com/35702532/86249798-be864c80-bb7d-11ea-968b-fe3dc3419469.png)

![image](https://user-images.githubusercontent.com/35702532/86249711-a4e50500-bb7d-11ea-95ef-5623f8010f6c.png)

**Comment by tprelog** [comment]
Hi @Ekristoffe -- I have not forgotten about this

<s>I found one issue that prevents this from being  something I can just quickly add ( to the `rc.d` scrip ).  Basically, while creating the plugin, Node-RED is installed by the user `root` however the `rc.d` script is run by user `nodered` -- Because the original install permission are set by `root`, the regular user `nodered` is unable to update the service.

I have been busy with real life so I have not had a chance to investigate a correct solution to include the "nodered upgrade" with the service script. Worst case will be needing a small "helper" script that is separate from the `rc.d` script.</s>

**Comment by tprelog** [comment]
@Ekristoffe - I found was having a separate issue -- Adding the `upgrade` function to the rc.d script does work as expected

You can Plugins > UPDATE your Node-RED plugin using the FreeNAS UI and this will get the updated service script.

Using the updated service script, you can upgrade Node-RED at any time to the latest version using
```
iocage console $_JAIL
service nodered upgrade
```

**Comment by tprelog** [comment]
As stated, the version displayed in the UI is linked to a package in the FreeBSD repository.

ESPHome is installed using npm, this is not a packaged application. Therefor it is not possible to display a version number in the TrueNAS UI

Other discussion here is unrelated to the original issue, but still everything mentioned has been resolved.
